version: 2

jobs:

  build-static:
    docker:
    - image: circleci/node:latest
    working_directory: /tmp/web
    steps:
    - checkout
    - restore_cache:
        keys:
        - dependencies-{{ checksum "package.json" }}
        - dependencies-
    - run:
        command: yarn
    - save_cache:
        paths:
        - node_modules
        key: dependencies-{{ checksum "package.json" }}
    - run:
        command: yarn ci
    - persist_to_workspace:
        root: /tmp/web
        paths:
        - public/*
        - .git/*

  deploy-to-gh-pages:
    docker:
    - image: circleci/node:latest
    working_directory: /tmp/web
    steps:
    - add_ssh_keys:
        fingerprints:
          - "42:ef:ba:37:87:eb:32:98:02:b1:68:82:04:58:25:6e"
    - attach_workspace:
        at: /tmp/web
    - run:
        name: Add Github.com to known_hosts
          # !!! Not recommended !!! 
          # https://www.freebsd.org/cgi/man.cgi?query=ssh-keyscan&manpath=SuSE+Linux/i386+11.3#security
        command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - run:
        name: Configure Git
        command: |
          git config --global user.email "mail+auto@chrisrenfrow.me"
          git config --global user.name "Autocrenfrow"
    - run:
        name: Github Pages deploy
        command: |
          git checkout gh-pages
          cp -r public/* .
          rm -rf public/
          git add . && git commit -m "Automated deploy (${CIRCLE_BUILD_URL})"
          git push origin gh-pages

workflows:
  version: 2

  build:
    jobs:
    - build-static:
        filters:
          branches:
            only: 
            - master
            - /feature-.*/

    - deploy-to-gh-pages:
        requires:
        - build-static
        filters:
          branches:
            only: master