version: 2

jobs:

  build:
    docker:
    - image: circleci/node:latest
    working_directory: /tmp/web
    steps:
    - checkout
    - restore_cache:
        keys:
        - dependencies-{{ checksum "package.json" }}
        - dependencies-

    - run:
        command: yarn

    - save_cache:
        paths:
        - node_modules
        key: dependencies-{{ checksum "package.json" }}
    - run:
        command: yarn ci
    - persist_to_workspace:
        root: /tmp/web
        paths:
        - public/*
        - .git/*

  deploy:
    docker:
    - image: circleci/node:latest
    working_directory: /tmp/web
    steps:
    - attach_workspace:
        at: /tmp/web
    - run:
        name: Github Pages Deploy
        command: |
          git checkout gh-pages
          ls
          mv -f public/* .
          git diff

workflows:
  version: 2

  build:
    jobs:
    - build:
        filters:
          branches:
            only: 
            - master
            - /feature-.*/

    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master