version: 2

jobs:

  build:
    docker:
    - image: circleci/node:latest
    working_directory: /tmp/web
    steps:
    - checkout
    - restore_cache:
        keys:
        - dependencies-{{ checksum "package.json" }}
        - dependencies-

    - run:
        command: yarn

    - save_cache:
        paths:
        - node_modules
        key: dependencies-{{ checksum "package.json" }}
    - run:
        command: yarn ci
    - persist_to_workspace:
        root: /tmp/web
        paths:
        - public/*
        - .git/*

  deploy:
    docker:
    - image: circleci/node:latest
    working_directory: /tmp/web
    steps:
    - add_ssh_keys:
        fingerprints:
          - "42:ef:ba:37:87:eb:32:98:02:b1:68:82:04:58:25:6e"
    - attach_workspace:
        at: /tmp/web
    - run:
        name: Github Pages Deploy
        command: |
          git config --global user.email "mail@chrisrenfrow.me"
          git config --global user.name "Chris Renfrow"
          git checkout gh-pages
          cp -r public/* .
          rm -rf public/
          git commit -am "Automated deploy from build \#${CIRCLE_BUILD_NUM}"
          git push origin gh-pages

workflows:
  version: 2

  build:
    jobs:
    - build:
        filters:
          branches:
            only: 
            - master
            - /feature-.*/

    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master