version: 2

jobs:
  build:
    docker:
    - image: circleci/node:latest
    steps:
    - checkout

    - restore_cache:
        keys:
        - dependencies-{{ checksum "package.json" }}
        - dependencies-

    - run:
        command: |
          yarn

    - save_cache:
        paths:
        - node_modules
        key: dependencies-{{ checksum "package.json" }}
    - run:
        command: yarn ci && ls
  deploy:
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - run:
        command: yarn deploy

workflows:
  version: 2

  ci:
    jobs:
    - build

  build:
    jobs:
    - build:
        filters:
          branches:
            only: master
    - deploy:
        filters:
          branches:
            only: master